// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Collection struct {
	ID   int32
	Name sql.NullString
}

type CollectionWord struct {
	ID           int32
	VobID        sql.NullInt32
	CollectionID sql.NullInt32
}

type Example struct {
	ID      int32
	MeanID  sql.NullInt32
	Example sql.NullString
}

type Mean struct {
	ID      int32
	PartID  sql.NullInt32
	Meaning sql.NullString
	Level   sql.NullString
}

type Pronounce struct {
	ID        int32
	AudioSrc  sql.NullString
	LocalFile sql.NullString
	Region    sql.NullString
	Pro       sql.NullString
	PartID    sql.NullInt32
}

type Vob struct {
	ID        int32
	Word      sql.NullString
	CreatedAt sql.NullTime
}

type VobPart struct {
	ID    int32
	VobID sql.NullInt32
	Type  sql.NullString
	Title sql.NullString
}
