// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const getExamples = `-- name: GetExamples :many
SELECT id, mean_id, example FROM examples e
WHERE e.mean_id IN (/*SLICE:mean_ids*/?)
`

func (q *Queries) GetExamples(ctx context.Context, meanIds []sql.NullInt32) ([]Example, error) {
	query := getExamples
	var queryParams []interface{}
	if len(meanIds) > 0 {
		for _, v := range meanIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:mean_ids*/?", strings.Repeat(",?", len(meanIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:mean_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Example
	for rows.Next() {
		var i Example
		if err := rows.Scan(&i.ID, &i.MeanID, &i.Example); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeans = `-- name: GetMeans :many
SELECT id, vob_id, meaning FROM means m
WHERE m.vob_id IN (/*SLICE:vob_ids*/?)
`

func (q *Queries) GetMeans(ctx context.Context, vobIds []sql.NullInt32) ([]Mean, error) {
	query := getMeans
	var queryParams []interface{}
	if len(vobIds) > 0 {
		for _, v := range vobIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:vob_ids*/?", strings.Repeat(",?", len(vobIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:vob_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mean
	for rows.Next() {
		var i Mean
		if err := rows.Scan(&i.ID, &i.VobID, &i.Meaning); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVobsCollection = `-- name: GetVobsCollection :many
SELECT v.id, v.word FROM
collections c, collection_words cw, vobs v
WHERE c.id = cw.collection_id 
AND cw.vob_id = v.id
AND c.name = ? ORDER BY RAND()
`

func (q *Queries) GetVobsCollection(ctx context.Context, name sql.NullString) ([]Vob, error) {
	rows, err := q.db.QueryContext(ctx, getVobsCollection, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vob
	for rows.Next() {
		var i Vob
		if err := rows.Scan(&i.ID, &i.Word); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
